export const IPC_CHANNELS = {
  OLLAMA: {
    CHECK_STATUS: 'ollama:checkStatus',
    START: 'ollama:start',
    STOP: 'ollama:stop',
    RESTART: 'ollama:restart',
    GET_CONFIG: 'ollama:getConfig',
    UPDATE_CONFIG: 'ollama:updateConfig',
    GET_MODELS: 'ollama:getModels',
    CHAT: 'ollama:chat',
    STREAM_CHAT: 'ollama:streamChat',
    PULL_MODEL: 'ollama:pullModel',
    DELETE_MODEL: 'ollama:deleteModel',
    GET_MODEL_INFO: 'ollama:getModelInfo',
    COPY_MODEL: 'ollama:copyModel',
    GENERATE_EMBEDDING: 'ollama:generateEmbedding',
    PS: 'ollama:ps',
    CREATE_MODEL: 'ollama:createModel',
  },
  FILE: {
    SELECT_FOLDER: 'file:selectFolder',
    SELECT_FILE: 'file:selectFile',
    READ_FILE: 'file:readFile',
  },
  STORAGE: {
    GET_MODULE_PATH: 'storage:getModulePath',
    SAVE_MODULE_PATH: 'storage:saveModulePath',
    CHECK_ALL_PATHS: 'storage:checkAllPaths',
    MIGRATE_MODULE_DATA: 'storage:migrateModuleData',
    PATH_NOT_CONFIGURED: 'storage:pathNotConfigured',
  },
  WINDOW: {
    MINIMIZE: 'window:minimize',
    MAXIMIZE: 'window:maximize',
    CLOSE: 'window:close',
    GET_MAXIMIZED: 'window:getMaximized',
  },
} as const;
